### ISSUE TITLE
Test Task List

### ISSUE THREAD

**Issue by arindambiswas1** [arindambiswas1/whatsapp-webhook-demo#1]
### Checklist for Whatsapp Notification feature

- [x] Add Registration Whatsapp notification option in Schedule a Notification Option
- [x] Add Registration Whatsapp notification option in Schedule a Notification Option 2
- [x] Setting up templates for WhatsApp Registration Notification for different types of event
- [x] Send WhatsApp notification if it is scheduled before
- [x] Add options to add Registration Whatsapp Notification from the Admin app (when whats app notification is created on the administration side it should reflect the newly created event)
- [x] Add Whatsapp Connection Setup option on Integration Page

- [x] Add send WhatsApp invite option in send invite form
- [x] Setting up templates for different types of event
- [x] Implement send now feature
- [x] Implement Schedule invite feature
- [x] Implement Save as Draft feature
- [x] Setup webhook for WhatsApp
  - [x] Add API for webhook verification
  - [x] Add API for getting webhook data
- [x] Modify analytic data based on status
- [x] Modify invites grid for WhatsApp invite data
- [x] Showing Whatsapp invites on the Invitation History Grid
- [x] Detail view for Whatsapp invites from Invitation History Grid
- [x] Edit invites form for Whatsapp invites at Invitation History Grid detail view
- [ ] Add Whatsapp template detail view in Registration detail view -> Emails grid
- [ ] Add country code field with the mobile number at the Registration site
